[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://isafarinetworkglobal-2.onrender.com/api"
  VITE_API_URL = "https://isafarinetworkglobal-2.onrender.com/api"
  VITE_FRONTEND_URL = "https://isafari-tz.netlify.app"
  VITE_NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://isafarinetworkglobal-2.onrender.com/api"
  VITE_API_URL = "https://isafarinetworkglobal-2.onrender.com/api"
  VITE_FRONTEND_URL = "https://isafari-tz.netlify.app"
  VITE_NODE_ENV = "production"
