services:
  - type: web
    name: backend-bncb
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: isafari_global_super_secret_jwt_key_2024_production
      - key: SESSION_SECRET
        value: isafari_session_secret_key_2024
      - key: FRONTEND_URL
        value: https://isafari-global.netlify.app
      - key: MONGODB_URI
        value: mongodb+srv://mfungojoctan01_db_user:%40Jctnftr01@cluster0.yvx6dyz.mongodb.net/iSafari-Global?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGODB_DB_NAME
        value: iSafari-Global
